version: "3.9"

services:
  # 🔹 Reverse Proxy
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Se usar SSL real
    depends_on:
      - matchmaking
      - game
      - persistence
      - keycloak

  # 🔹 Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  # 🔹 Matchmaking Service (Flask/FastAPI)
  matchmaking:
    build: ./services/matchmaking
    container_name: matchmaking-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    ports:
      - "5001:5000"

  # 🔹 Game Service (Flask-SocketIO)
  game:
    build: ./services/game
    container_name: game-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
    ports:
      - "5002:5000"

  # 🔹 Persistence Service (Flask/FastAPI + SQLAlchemy)
  persistence:
    build: ./services/persistence
    container_name: persistence-service
    environment:
      - DATABASE_URL=postgresql://game:gamepass@postgres:5432/gamedb
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
    ports:
      - "5003:5000"

  # 🔹 Frontend (React)
  frontend:
    build: ./frontend
    container_name: frontend
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_API_URL=/api
      - REACT_APP_WS_URL=/ws
    ports:
      - "3000:3000"

  # 🔹 Redis (queue + cache)
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # 🔹 PostgreSQL (persistent DB)
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=game
      - POSTGRES_PASSWORD=gamepass
      - POSTGRES_DB=gamedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: