version: '3.9'

services:
  # ==========================
  # PostgreSQL
  # ==========================
  db:
    image: postgres:15
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cardgame
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # ==========================
  # Redis
  # ==========================
  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - backend

  # ==========================
  # Flask Backend
  # ==========================
  backend:
    build:
      context: ./backend
    container_name: flask-backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cardgame
    networks:
      - frontend
      - backend

  # ==========================
  # Next.js Frontend
  # ==========================
  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    restart: always
    networks:
      - frontend

  # ==========================
  # Nginx Reverse Proxy
  # ==========================
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
      - backend

volumes:
  pgdata:

networks:
  frontend:
  backend:
